server:
  port: 8761  #端口号

eureka:
  instance:
    hostname: localhost  #localhost
  client:
    registerWithEureka: true  #注册到Eureka上
    fetchRegistry: true #从Eureka上拉取信息
    serviceUrl:
      defaultZone: http://root:root@localhost:8762/eureka
  server:
    enable-self-preservation: true  #自我保护机制
#指定用户名和密码
spring:
  application:
    name: EUREKA
  security:
    user:
      name: root
      password: root
